# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.2
    hooks:
      - id : black-jupyter
        # It is recommended to specify the latest version of Python
        # supported by your project here, or alternatively use
        # pre-commit's default_language_version, see
        # https://pre-commit.com/#top_level-default_language_version
        language_version: python3.12
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: requirements-txt-fixer
    -   id: mixed-line-ending
    -   id: check-toml
    -   id: check-merge-conflict
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.5.1
    hooks:
      - id: ruff
      # Run the linter.
      - id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]
# - repo: local
#   hooks:
    # - id: simple-pylint
    #   name: simple-pylint
    #   entry: pylint
    #   args: ["api/"]
    #   language: system
    #   types: [python]
    #   pass_filenames: false

    # - id: inline-pylint-with-bash
    #   name: inline-pylint-with-bash
    #   entry: bash -c 'lines=$(pylint api/ | wc -l) && (( lines > 10)) && exit 1'
    #   language: system
    #   types: [python]
    #   pass_filenames: false

    # - id: check-special-files
    #   name: check-special-files
    #   entry: bash .pre-commit-hooks/check-special-files.sh
    #   language: system
    #   types: [python]
    #   pass_filenames: false

default_language_version:
  python: python3.12

default_stages: [commit, push]
