# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/ambv/black
    rev: 23.7.0
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: requirements-txt-fixer
    -   id: mixed-line-ending
    -   id: check-toml
    -   id: check-merge-conflict
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.0.285
  hooks:
    - id: ruff
# - repo: local
#   hooks:
    # - id: simple-pylint
    #   name: simple-pylint
    #   entry: pylint
    #   args: ["api/"]
    #   language: system
    #   types: [python]
    #   pass_filenames: false

    # - id: inline-pylint-with-bash
    #   name: inline-pylint-with-bash
    #   entry: bash -c 'lines=$(pylint api/ | wc -l) && (( lines > 10)) && exit 1'
    #   language: system
    #   types: [python]
    #   pass_filenames: false

    # - id: check-special-files
    #   name: check-special-files
    #   entry: bash .pre-commit-hooks/check-special-files.sh
    #   language: system
    #   types: [python]
    #   pass_filenames: false

default_language_version:
  python: python3.11

default_stages: [commit, push]
